export {default as AddPost} from './AddPost/AddPost'
export {default as Homepage} from './Homepage'
export {default as Login} from './Login'
export {default as Register} from './Register'
export {default as SinglePost} from './SinglePost'